/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversations
         * @description Conversazioni proprie, dalle più recenti, con paginazione a cursore.
         */
        get: operations["list_conversations_api_v1_conversations_get"];
        put?: never;
        /**
         * Create Conversation
         * @description Nuova conversazione posseduta dal principal (§7.2).
         */
        post: operations["create_conversation_api_v1_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description Conversazione per ID; fuori scope → 404 (§7.3).
         */
        get: operations["get_conversation_api_v1_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Conversation
         * @description Cancellazione fisica con i messaggi (cascata, migration 0002).
         *
         *     Con ``expected_updated_at`` (query), versione attesa: stato cambiato
         *     dall'ultima lettura del client → 409.
         */
        delete: operations["delete_conversation_api_v1_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        /**
         * Rename Conversation
         * @description Cambia il titolo: aggiorna ``updated_at`` (ordine della lista).
         *
         *     Con ``expected_updated_at`` nel body, versione attesa: stato
         *     cambiato dall'ultima lettura del client → 409.
         */
        patch: operations["rename_conversation_api_v1_conversations__conversation_id__patch"];
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Messages
         * @description Messaggi in ordine di sequenza, da ``after_sequence`` escluso.
         */
        get: operations["list_messages_api_v1_conversations__conversation_id__messages_get"];
        put?: never;
        /**
         * Create Message
         * @description Messaggio dell'utente: ruolo deciso dal server, sequenza server-side.
         *
         *     Con ``idempotency_key``, il retry della stessa richiesta non
         *     duplica il messaggio; stessa chiave con contenuto diverso → 409.
         */
        post: operations["create_message_api_v1_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview inline transitoria; usare i run durevoli quando disponibili
         * @deprecated
         */
        post: operations["run_chat_api_v1_conversations__conversation_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Run
         * @description Accoda un run durevole; il worker lo consuma in background (P-05).
         */
        post: operations["create_run_api_v1_conversations__conversation_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Utente corrente: identità risolta dal server, mai dal client.
         */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description Catalogo dei modelli del runtime di inference locale (§9.1).
         */
        get: operations["list_models_api_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Model Readiness
         * @description Diagnostica autenticata e read-only del modello pilot configurato.
         */
        get: operations["model_readiness_api_v1_models_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Profiles
         * @description Profili propri con versione, binding e disponibilità del modello.
         */
        get: operations["list_profiles_api_v1_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provision Default
         * @description Provisioning esplicito e idempotente del solo Assistente.
         */
        post: operations["provision_default_api_v1_profiles_defaults_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{profile_id}/binding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve Binding
         * @description Snapshot riproducibile della risoluzione del binding (ADR 0003).
         *
         *     Modello assente dal catalogo → 503 ``MODEL_UNAVAILABLE``
         *     recuperabile, mai un fallback invisibile.
         */
        get: operations["resolve_binding_api_v1_profiles__profile_id__binding_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{profile_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Switch Model
         * @description Nuova versione del profilo con un modello diverso (B-02.1).
         *
         *     Crea sempre un binding e una versione nuovi, mai una modifica
         *     in-place. ``expected_profile_version`` obsoleta o chiave di
         *     idempotenza riusata con payload diverso → 409. Modello assente
         *     dal catalogo → 503 ``MODEL_UNAVAILABLE`` recuperabile.
         */
        post: operations["switch_model_api_v1_profiles__profile_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Snapshot del run; fuori scope → 404 (§7.3).
         */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bootstrap
         * @description Bootstrap locale monouso del proprietario (NewRay.md §20.3).
         *
         *     Crea organizzazione, proprietario e sessione, ed emette il cookie
         *     opaco con HttpOnly/SameSite. Se il proprietario esiste già,
         *     ``CONFLICT`` (409): il bootstrap non può essere ripetuto e non
         *     accetta il solo nome come credenziale (B-03.2-14).
         */
        post: operations["bootstrap_api_v1_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Rientro autenticato del proprietario esistente (B-03.2-14).
         *
         *     Ogni chiamata riuscita apre una **nuova** sessione: le
         *     precedenti restano gestibili con la revoca; nessun riuso del
         *     cookie in circolo. Errore uniforme ``INVALID_CREDENTIALS`` per
         *     owner assente o credenziale sbagliata; ``CREDENTIAL_NOT_SET`` è
         *     il segnale al percorso di recupero locale, non un login riuscito.
         */
        post: operations["login_api_v1_session_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke
         * @description Revoca immediata e idempotente della sessione in corso (§22.2 #4).
         */
        post: operations["revoke_api_v1_session_revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Status
         * @description Stato pubblico dell'installazione (B-03.2-14).
         *
         *     Nessuna informazione derivata dal cookie o dall'owner reale:
         *     solo la presenza di un proprietario. Serve alla WebUI per
         *     decidere fra schermata bootstrap e schermata login senza
         *     tentare bootstrap e leggere il ``CONFLICT`` come segnale.
         */
        get: operations["status_api_v1_session_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AProfile
         * @description Profili AI selezionabili manualmente dall'utente.
         * @enum {string}
         */
        AProfile: "assistant" | "researcher" | "coder";
        /**
         * BindingDTO
         * @description Binding del profilo a runtime e modello, con parametri espliciti.
         */
        BindingDTO: {
            /** Model Name */
            model_name: string;
            /** Name */
            name: string;
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /** Runtime */
            runtime: string;
        };
        /**
         * BootstrapRequest
         * @description Richiesta di bootstrap monouso: nome del proprietario + credenziale.
         *
         *     La credenziale non viene mai persistita in chiaro: il caso d'uso ne
         *     calcola il record hash con ``newray.kernel.crypto`` (B-03.2-14). La
         *     lunghezza minima applicativa è verificata dal kernel; qui il limite
         *     superiore protegge da payload gonfiati senza fare da oracolo
         *     sull'algoritmo di hashing.
         */
        BootstrapRequest: {
            /** Credential */
            credential: string;
            /** Display Name */
            display_name: string;
        };
        /**
         * ConversationDTO
         * @description Conversazione nel profilo pubblico: nessun campo oltre il necessario.
         */
        ConversationDTO: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ConversationListDTO
         * @description Pagina di conversazioni con cursore per la pagina successiva (§19.2).
         */
        ConversationListDTO: {
            /** Items */
            items: components["schemas"]["ConversationDTO"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * CreateConversationRequest
         * @description Creazione di una conversazione: solo il titolo, il resto è del server.
         */
        CreateConversationRequest: {
            /** Title */
            title: string;
        };
        /**
         * CreateMessageRequest
         * @description Messaggio dell'utente: il ruolo è deciso dal server, mai dal payload.
         *
         *     ``idempotency_key`` opzionale: il retry della stessa richiesta
         *     restituisce lo stesso messaggio senza duplicarlo; stessa chiave con
         *     contenuto diverso risponde 409.
         */
        CreateMessageRequest: {
            /** Content */
            content: string;
            /** Idempotency Key */
            idempotency_key?: string | null;
        };
        /**
         * CreateRunRequest
         * @description Creazione di un run durevole: profilo, messaggio e idempotenza.
         *
         *     ``idempotency_key`` è obbligatoria: il retry della stessa richiesta
         *     restituisce lo stesso run senza rieseguirlo; stessa chiave con
         *     contenuto/profilo diverso risponde 409.
         */
        CreateRunRequest: {
            /** Content */
            content: string;
            /** Idempotency Key */
            idempotency_key: string;
            /**
             * Profile Id
             * Format: uuid
             */
            profile_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IdentityDTO
         * @description Identità pubblica del principal risolto dal server.
         *
         *     Niente campi sensibili oltre il minimo necessario alla WebUI:
         *     nessun token, nessun dettaglio della sessione.
         */
        IdentityDTO: {
            /** Display Name */
            display_name: string;
            role: components["schemas"]["Role"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * LoginRequest
         * @description Richiesta di login del proprietario esistente (B-03.2-14).
         *
         *     Owner sconosciuto e credenziale sbagliata collassano in un unico
         *     ``INVALID_CREDENTIALS``: il canale non è un oracolo per scoprire il
         *     nome scelto in bootstrap.
         */
        LoginRequest: {
            /** Credential */
            credential: string;
            /** Display Name */
            display_name: string;
        };
        /**
         * MessageDTO
         * @description Messaggio della conversazione, con sequenza e ruolo noti al server.
         */
        MessageDTO: {
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            role: components["schemas"]["MessageRole"];
            /** Sequence */
            sequence: number;
        };
        /**
         * MessageListDTO
         * @description Pagina di messaggi, in ordine di sequenza crescente.
         *
         *     ``next_sequence`` è l'ultimo valore ricevuto: se presente va passato
         *     invariato come ``after_sequence`` per ottenere la pagina successiva.
         */
        MessageListDTO: {
            /** Items */
            items: components["schemas"]["MessageDTO"][];
            /** Next Sequence */
            next_sequence: number | null;
        };
        /**
         * MessageRole
         * @description Autore del messaggio, noto al server: mai derivato dal client (§7.1).
         * @enum {string}
         */
        MessageRole: "user" | "assistant";
        /**
         * ModelInfoDTO
         * @description Modello del runtime con digest e stato (NewRay.md §9.1).
         *
         *     Il digest identifica l'artefatto per la riproducibilità; i tag
         *     mobili restano scoperta, mai riferimento degli snapshot.
         */
        ModelInfoDTO: {
            /** Capabilities */
            capabilities: string[];
            /** Digest */
            digest: string | null;
            /** Name */
            name: string;
            /** Runtime */
            runtime: string;
            status: components["schemas"]["ModelStatus"];
        };
        /**
         * ModelListDTO
         * @description Catalogo del runtime di inference locale (NewRay.md §9.1).
         */
        ModelListDTO: {
            /** Items */
            items: components["schemas"]["ModelInfoDTO"][];
        };
        /**
         * ModelReadinessDTO
         * @description Stato osservato del candidato; capacità dichiarate non qualificate.
         */
        ModelReadinessDTO: {
            /** Declared Capabilities */
            declared_capabilities: string[];
            /** Digest */
            digest: string | null;
            /** Model Name */
            model_name: string | null;
            state: components["schemas"]["ReadinessState"];
        };
        /**
         * ModelStatus
         * @description Stati distinti del catalogo (NewRay.md §9.1): essere installati,
         *     compatibili e qualificati sono fatti diversi.
         * @enum {string}
         */
        ModelStatus: "installed" | "compatible" | "qualified";
        /**
         * ProfileDTO
         * @description Profilo con versione corrente, binding e disponibilità del modello.
         *
         *     ``model`` è ``null`` quando il modello del binding non è nel
         *     catalogo: la risoluzione risponde ``MODEL_UNAVAILABLE`` (§19.4).
         */
        ProfileDTO: {
            binding: components["schemas"]["BindingDTO"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["AProfile"];
            model: components["schemas"]["ModelInfoDTO"] | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: string;
        };
        /**
         * ProfileListDTO
         * @description Profili propri: collezione piccola e finita, senza paginazione.
         */
        ProfileListDTO: {
            /** Items */
            items: components["schemas"]["ProfileDTO"][];
        };
        /**
         * ReadinessState
         * @description Diagnostica del candidato, distinta dalla qualifica delle capacità.
         * @enum {string}
         */
        ReadinessState: "not_configured" | "unreachable" | "runtime_error" | "catalog_empty" | "model_missing" | "artifact_incompatible" | "installed_unverified";
        /**
         * RenameConversationRequest
         * @description Rinomina di una conversazione.
         *
         *     ``expected_updated_at`` è la versione attesa (il campo ``updated_at``
         *     dell'ultima lettura del client): se la conversazione è cambiata nel
         *     frattempo la mutazione risponde 409, mai una sovrascrittura silenziosa.
         */
        RenameConversationRequest: {
            /** Expected Updated At */
            expected_updated_at?: string | null;
            /** Title */
            title: string;
        };
        /**
         * ResolvedBindingDTO
         * @description Snapshot della risoluzione del binding: riproducibile (ADR 0003).
         *
         *     Stesso profilo sullo stesso stato del catalogo → stesso payload.
         */
        ResolvedBindingDTO: {
            /**
             * Binding Id
             * Format: uuid
             */
            binding_id: string;
            /** Binding Name */
            binding_name: string;
            /** Capabilities */
            capabilities: string[];
            /** Digest */
            digest: string;
            /** Instructions */
            instructions: string;
            /** Model Name */
            model_name: string;
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /**
             * Profile Id
             * Format: uuid
             */
            profile_id: string;
            /** Profile Version */
            profile_version: string;
            /**
             * Profile Version Id
             * Format: uuid
             */
            profile_version_id: string;
            /** Runtime */
            runtime: string;
        };
        /**
         * Role
         * @description Ruolo account del principal (NewRay.md §7.1, 7.2).
         *
         *     Asse separato dal profilo AI: non descrive capacità del modello né
         *     strumenti disponibili.
         * @enum {string}
         */
        Role: "owner" | "member" | "administrator";
        /**
         * RunDTO
         * @description Snapshot pubblico del run: stato e progresso, non il binding interno.
         */
        RunDTO: {
            /** Completion Tokens */
            completion_tokens: number | null;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Eval Duration Ns */
            eval_duration_ns: number | null;
            /** Finish Reason */
            finish_reason: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Partial Text */
            partial_text: string;
            /** Prompt Tokens */
            prompt_tokens: number | null;
            state: components["schemas"]["RunState"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RunRequest
         * @description Richiesta di generazione: messaggio utente e profilo selezionato.
         */
        RunRequest: {
            /** Content */
            content: string;
            /**
             * Profile Id
             * Format: uuid
             */
            profile_id: string;
        };
        /**
         * RunState
         * @enum {string}
         */
        RunState: "queued" | "running" | "waiting_approval" | "completed" | "failed" | "cancelled" | "interrupted";
        /**
         * SessionStatusDTO
         * @description Stato pubblico dell'installazione (``GET /session/status``).
         *
         *     Serve alla WebUI per decidere se mostrare bootstrap o login; non
         *     rivela il nome dell'owner né alcun dettaglio derivato dalla
         *     sessione, solo la presenza dell'owner.
         */
        SessionStatusDTO: {
            /** Bootstrapped */
            bootstrapped: boolean;
        };
        /**
         * SwitchProfileModelRequest
         * @description Nuova versione del profilo con un modello diverso (B-02.1).
         *
         *     ``expected_profile_version`` è l'optimistic lock: il valore
         *     ``version`` dell'ultima lettura del profilo. Se il profilo è
         *     cambiato nel frattempo la richiesta risponde 409, mai una
         *     sovrascrittura silenziosa. ``idempotency_key`` opzionale: il retry
         *     della stessa richiesta restituisce lo stesso esito senza duplicarlo;
         *     stessa chiave con payload diverso risponde 409. ``instructions``
         *     assente mantiene quelle della versione corrente.
         */
        SwitchProfileModelRequest: {
            /** Expected Profile Version */
            expected_profile_version?: string | null;
            /** Idempotency Key */
            idempotency_key?: string | null;
            /** Instructions */
            instructions?: string | null;
            /** Model Name */
            model_name: string;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_conversations_api_v1_conversations_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationListDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_api_v1_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_v1_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_v1_conversations__conversation_id__delete: {
        parameters: {
            query?: {
                expected_updated_at?: string | null;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_conversation_api_v1_conversations__conversation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameConversationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_api_v1_conversations__conversation_id__messages_get: {
        parameters: {
            query?: {
                after_sequence?: number;
                limit?: number;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageListDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_message_api_v1_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_chat_api_v1_conversations__conversation_id__run_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_v1_conversations__conversation_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityDTO"];
                };
            };
        };
    };
    list_models_api_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelListDTO"];
                };
            };
        };
    };
    model_readiness_api_v1_models_readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelReadinessDTO"];
                };
            };
        };
    };
    list_profiles_api_v1_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileListDTO"];
                };
            };
        };
    };
    provision_default_api_v1_profiles_defaults_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDTO"];
                };
            };
        };
    };
    resolve_binding_api_v1_profiles__profile_id__binding_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolvedBindingDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    switch_model_api_v1_profiles__profile_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchProfileModelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bootstrap_api_v1_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BootstrapRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_session_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_v1_session_revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    status_api_v1_session_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStatusDTO"];
                };
            };
        };
    };
}
