"""Modulo models: catalogo dei modelli e inference (NewRay.md §§6.1, 9.1; B-03).

L'API pubblica è ``public.py``; qui si riesportano solo i nomi pubblici,
così ``from newray.modules.models import ...`` resta l'unico punto di
import per i consumatori (mai ``adapters`` né dettagli privati altrui).
"""

from newray.modules.models.public import (
    DEFAULT_MODEL_NAME,
    MAX_CHAT_MESSAGE_LENGTH,
    MAX_MODEL_NAME_LENGTH,
    RUNTIME_OLLAMA,
    CampaignConfig,
    CampaignResult,
    ChatMessage,
    ChatModel,
    ChatRequest,
    ChatRole,
    Completion,
    ContentDelta,
    HardwareFingerprint,
    ModelCatalog,
    ModelInfo,
    ModelReadiness,
    ModelStatus,
    ProbeOutcome,
    QualificationRecord,
    QualificationStore,
    ReadinessState,
    RuntimeProbe,
    StreamEvent,
    discover_hardware,
    qualified_capabilities_for,
    run_campaign,
)

__all__ = [
    "CampaignConfig",
    "CampaignResult",
    "ChatMessage",
    "ChatModel",
    "ChatRequest",
    "ChatRole",
    "Completion",
    "ContentDelta",
    "DEFAULT_MODEL_NAME",
    "HardwareFingerprint",
    "MAX_CHAT_MESSAGE_LENGTH",
    "MAX_MODEL_NAME_LENGTH",
    "ModelCatalog",
    "ModelInfo",
    "ModelReadiness",
    "ModelStatus",
    "ProbeOutcome",
    "QualificationRecord",
    "QualificationStore",
    "ReadinessState",
    "RUNTIME_OLLAMA",
    "RuntimeProbe",
    "StreamEvent",
    "discover_hardware",
    "qualified_capabilities_for",
    "run_campaign",
]
